### ISSUE TITLE
feature request: track ongoing issues in issues, not wiki

### ISSUE THREAD

**Issue by leahbannon** [18F/cg-postmortems#1]
- easier to follow
- others can add questions/comments related to the issue that are not immediately relevant (e.g., I don't want to get in the way of the ongoing resolution of the problem, but I'd like to ask about the time of day changes are pushed and if heads up is possible)

**Comment by jezhumble** [comment]
Thanks Leah. This repo is not for managing or tracking ongoing issues, it’s just for post-mortems. If you want to know what’s up with an ongoing issue or ask questions, the #cloud-gov-support channel is the place to be. In particular, the timeline in the wiki should not be relied on as a guide to the current status, the place to visit for that is http://cloudgov.statuspage.io/. I'm going to update the front page of this repo with this information and close the issue.
