### ISSUE TITLE
Security Groups outage

### ISSUE THREAD

**Issue by jezhumble** [18F/cg-postmortems#2]
At 9:28am Pacific Time on 8 March a change was made to the security group settings in AWS by a contractor at Aquilent. This change restricted outbound traffic on the Cloud.gov PAAS. The change was part of a number of changes being made as part of the process to achieve ATO for the platform. However a number of applications running on cloud.gov relied upon outbound traffic to access services they depended upon, and some of this traffic was blocked, leading to the applications being unavailable. At one point, all applications running on Cloud.gov were unavailable.

While attempts were made to add exceptions for individual applications, which restored service to some of the applications, ultimately a decision was made to roll back the change, restoring service to all applications at 8:00am Pacific Time on 9 March.

A postmortem was held at 1:30pm Pacific Time on 10 March: [Timeline](https://github.com/18F/cg-postmortems/wiki/2016-03-08-fec-outage-postmortem-timeline) | [Contributing Factors and Ideas for Improvement](https://stickies.io/boards/56e1e98c5d8d99cf31aa050c#1).

The following actions were proposed in order to prevent this type of outage from happening again:
- Get all security group configuration into version control, and use pull requests to get visibility into changes to be made, and control over triggering of these changes.
- Ensure applications running in cloud.gov are monitored and that the cloud.gov team gets alerts if they aren't operating as expected
- Use CF security groups instead of AWS security groups, and make the current state of these rules available to the cloud.gov team, and the teams using cloud.gov
- Create a notification system that allows us to notify the key contact for each application running on the platform
- Create a more accurate staging environment that allows us to test these changes in a more veridical fashion

We will be creating stories in our backlog to address these, and reviewing status in 2 months. Please add any comments you have below.

**Comment by hollyallen** [comment]
Thank you for this postmortem writeup. The link to stickies.io requires a login, should we get accounts? (Can login with Google, so no new account needed, can see the page now)

**Comment by NoahKunin** [comment]
@jezhumble:

This isn't making a technical decision in any way in a post-mortem thread but:

> Use CF security groups instead of AWS security groups, and make the current state of these rules available to the cloud.gov team, and the teams using cloud.gov

...is a huge change. AWS Security Groups are one of the core elements of the FedRAMP Authorization. We can compensate with CF Security Groups to be sure, but we have to tread lightly there and may have to alter a substantive amount of documentation. 

This may be the right technical call on a variety of levels, not pre-judging, just flagging that it may be a much larger feature to implement.

**Comment by NoahKunin** [comment]
@jezhumble Was this sufficiently vetted in May that we can close?

**Comment by jezhumble** [comment]
We never did the review - would you like to schedule one @mogul @dlapiduz ?

**Comment by dlapiduz** [comment]
To be honest I think that our procedures and systems had changed a lot since then. If you still want to do a review we can do it but I doubt any of it applies.

**Comment by NoahKunin** [comment]
I'm w/ @dlapiduz - we have an entirely different contractor now as well in this role. So let's consider this as part and parcel of what ops and continuous monitoring looks like in a post-FedRAMP world for cloud.gov, and close this issue out.

Feel free to re-open if anyone feels differently.
