### ISSUE TITLE
Text for external partners?

### ISSUE THREAD

**Issue by NoahKunin** [18F/cg-postmortems#3]
The README says: 

> Please note - if you are experiencing a problem or want to discuss an ongoing incident, please visit #cloud-gov-support in Slack, or visit http://cloudgov.statuspage.io/. This repository and wiki is only for post-mortems after the incident has been closed.

This speaks to 18F teams, but doesn't give external partners an easy route to raise their :hand:. 

We may just want to wait until Discourse is up to address this, just flagging so we don't forget.

**Comment by brittag** [comment]
Addressed in readme
