### ISSUE TITLE
Include impact to responder as part of post-mortem timeline/consequences

### ISSUE THREAD

**Issue by NoahKunin** [18F/cg-postmortems#5]
At the HumanOps SF meetup, PagerDuty staff made a great suggestion, that to understand the true impact of an incident or an outage on the organization, the emotional / focus impact on the responder should be included (i.e. incident commander had to stay 2 hours late, etc). 

I really like this. Thoughts?

**Comment by mogul** [comment]
I like it, and will bring it up at the next incident retro (which will happen really soon now...)
